### PR TITLE
new: Create a new shim executable.

### PR DESCRIPTION
**Pull request by milesj**

### CODE REVIEW

**Comment by rotu** [comment]
Go Miles! I'm super excited to have a shim solution that's not specific to the shell!

**Comment by rotu** [comment]
> @rotu So far this works perfectly for primary shims (npm, node, etc), but unfortunately doesn't work for secondary shims (npx, pip, etc).
> 
> The problem is that secondary shims add `--alt bin` flags and before/after args into the shell file, which are then passed to `proto`. When relying on `argv[0]`, we have lost this information.
> 
> The only solution I can think of is having some kind of manifest like `~/.proto/shims/manifest.json` that keeps a mapping of how everything should be executed.

Agreed, but I think secondary shims are a problem from the beginning. That's what I meant [in my comment](https://github.com/moonrepo/proto/issues/311#issuecomment-1834632142):

> 3. To that end, `proto` needs a way to map the name of a bin to the plugin/tool which provides it. I realize this is ambiguous (e.g. two plugins could declare a program with the same name) and `proto` needs to handle this either implicitly or by saving desired shims in the `.prototools` config.

I think the easiest thing is to add a section to the yaml, which maps the name to a `$PROTO_HOME`-relative path:

```yaml
[shims]
npm = "tools/npm/10.2.4/bin/npm"
```

This even provides the ability to shim to the *real* bundled `npm` instead of one provided by `node_depman_plugin`:

```yaml
[shims]
npm = "tools/node/20.10.0/bin/npm"
```

If these need to float with the version, the path could instead be, e.g. `tools/npm/${PROTO_NPM_VERSION}/bin/npm` or use some other placeholder like `proto:npm/bin/npm`.

**Comment by milesj** [comment]
Yup exactly. Will look into ways to easily solve this. This may land in 0.25 instead of 0.24. Want to ensure it all works correctly.

**Comment by rotu** [comment]
This also allows you to e.g. remap `node` like `bunx --bun` does:
```
[shims]
node = path/to/bun
```
or even possibly configure arguments on a per-project basis:
```
[shims]
node = ["path/to/node", "--loader", "ts-node/esm"]
```

**Pull request merged**
