### PR TITLE
fix: canary is not reinstalled unless install --force is used. #(618)

### LINKED ISSUE #618: Canary version is always detected as has not been installed even though already installed
### What version?

0.41.1

### Which command?

proto install

### What happened?

I tried installing deno and bun using the following commands
```
proto install deno canary
proto install bun canary
proto install --canary deno
proto install --canary bun
```
which successfully download and install the canary version

then running the tool using
```
PROTO_BUN_VERSION=canary bun
PROTO_DENO_VERSION=canary deno
```

always give the following error
```
Error: proto::tool::required

  × This project requires Bun canary, but this version has not been installed. Install it with proto install bun canary, or enable the auto-install setting to automatically install
  │ missing versions!
```
or
```
❯ PROTO_DENO_VERSION=canary deno
Error: proto::tool::required

  × This project requires Deno canary, but this version has not been installed. Install it with proto install deno canary, or enable the auto-install setting to automatically install
  │ missing versions!
```

enabling auto-install does allow the command to run, but only after installing it again, which is slowing things down and waste bandwidth.

Expectation is that once the canary version is installed, proto is able to resolve the installed tool and use it, and only reinstall the canary version when we requested it specifically with `proto install --canary deno|bun`

### Trace logs?

```
❯ PROTO_LOG=trace PROTO_DEBUG_COMMAND=1 PROTO_DENO_VERSION=canary deno
[DEBUG 2024-09-27 07:48:09.993] proto  Running proto v0.41.1  bin="/home/shanipribadi/.proto/bin/proto" args=["run", "deno"] shim="deno" shim_bin="/home/shanipribadi/.proto/shims/deno" pid=358605
[TRACE 07:48:10.007] starbase::app  Running startup phase
[DEBUG 07:48:10.007] proto_core::proto  Creating proto environment, detecting store  store="/home/shanipribadi/.proto" home="/home/shanipribadi"
[TRACE 07:48:10.007] starbase::app  Running analyze phase
[DEBUG 07:48:10.007] proto::systems  Loading configuration in upwards-global mode  working_dir="/home/shanipribadi/git/proto"
[DEBUG 07:48:10.007] proto_core::proto_config  Loading .prototools  file="/home/shanipribadi/git/proto/.prototools"
[TRACE 07:48:10.007] starbase_utils::fs  Reading file  file="/home/shanipribadi/git/proto/.prototools"
[TRACE 07:48:10.007] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 07:48:10.007] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="<code>"
[TRACE 07:48:10.007] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 07:48:10.007] proto_core::proto_config  Loading .prototools  file="/home/shanipribadi/.proto/.prototools"
[TRACE 07:48:10.007] starbase_utils::fs  Opening file  file="/home/shanipribadi/.proto/.prototools"
[TRACE 07:48:10.008] starbase_utils::fs_lock  Locking file  file="/home/shanipribadi/.proto/.prototools"
[TRACE 07:48:10.008] starbase_utils::fs_lock  Unlocking file  file="/home/shanipribadi/.proto/.prototools"
[TRACE 07:48:10.008] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 07:48:10.008] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="<code>"
[TRACE 07:48:10.008] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 07:48:10.008] proto_core::proto_config  Merging loaded configs with global
[DEBUG 07:48:10.008] proto_core::proto_config  Merged 2 configs
[DEBUG 07:48:10.008] proto_core::proto_config  Merging loaded configs without global
[DEBUG 07:48:10.008] proto_core::proto_config  Merged 1 configs
[TRACE 07:48:10.008] starbase::app  Running execute phase
[DEBUG 07:48:10.008] proto_core::tool_loader  Finding a configured plugin  tool="deno"
[DEBUG 07:48:10.008] proto_core::tool_loader  Using a built-in plugin  plugin="https://github.com/moonrepo/tools/releases/download/deno_tool-v0.12.0/deno_tool.wasm"
[TRACE 07:48:10.009] warpgate::loader  Creating plugin loader  cache_dir="/home/shanipribadi/.proto/plugins"
[TRACE 07:48:10.009] warpgate::loader  Loading plugin deno  id="deno" locator="https://github.com/moonrepo/tools/releases/download/deno_tool-v0.12.0/deno_tool.wasm"
[TRACE 07:48:10.009] starbase_utils::fs  Reading file metadata  file="/home/shanipribadi/.proto/plugins/deno-0c576e3fa327e68fc1896e3eb15866c63f35d549fc5fc64ca1f22c271c1c2a9b.wasm"
[TRACE 07:48:10.009] warpgate::loader  Plugin already downloaded and cached  id="deno" path="/home/shanipribadi/.proto/plugins/deno-0c576e3fa327e68fc1896e3eb15866c63f35d549fc5fc64ca1f22c271c1c2a9b.wasm"
[DEBUG 07:48:10.009] proto_core::tool_loader  Loading WASM plugin  source="/home/shanipribadi/.proto/plugins/deno-0c576e3fa327e68fc1896e3eb15866c63f35d549fc5fc64ca1f22c271c1c2a9b.wasm"
[TRACE 07:48:10.012] warpgate::plugin  Storing plugin identifier  id="deno"
[TRACE 07:48:10.012] warpgate::plugin  Storing host environment  id="deno" env={"arch":"x64","libc":"gnu","os":"linux","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"/home/shanipribadi"}}
[DEBUG 07:48:10.012] proto_core::tool  Creating tool deno and instantiating plugin
[DEBUG 07:48:10.012] warpgate::client  Creating HTTP client
[DEBUG 07:48:10.018] warpgate::client  Created HTTP client
[TRACE 07:48:10.018] warpgate::plugin  Creating plugin container  id="deno"
[TRACE 07:48:10.031] warpgate::plugin  Created plugin container  id="deno" plugin="5458864e-5738-44ad-84b0-97589df7749b"
[DEBUG 07:48:10.031] proto_core::tool  Created tool deno and its WASM runtime
[TRACE 07:48:10.031] warpgate::plugin  Calling guest function register_tool  id="deno" plugin="5458864e-5738-44ad-84b0-97589df7749b" input={"id":"deno"}
[TRACE 07:48:10.032] warpgate::plugin  Called guest function register_tool  id="deno" plugin="5458864e-5738-44ad-84b0-97589df7749b" output={"config_schema":{"name":"DenoPluginConfig","ty":{"type":"Struct","fields":{"dist-url":{"schema":{"ty":{"type":"String"}},"hidden":false,"nullable":false,"optional":true,"read_only":false,"write_only":false}},"partial":false}},"inventory":{},"name":"Deno","plugin_version":"0.12.0","self_upgrade_commands":["upgrade"],"type":"Language"}
[DEBUG 07:48:10.032] proto_core::tool_manifest  Loading manifest.json  file="/home/shanipribadi/.proto/tools/deno/manifest.json"
[TRACE 07:48:10.032] starbase_utils::fs  Opening file  file="/home/shanipribadi/.proto/tools/deno/manifest.json"
[TRACE 07:48:10.032] starbase_utils::fs_lock  Locking file  file="/home/shanipribadi/.proto/tools/deno/manifest.json"
[TRACE 07:48:10.032] starbase_utils::fs_lock  Unlocking file  file="/home/shanipribadi/.proto/tools/deno/manifest.json"
[DEBUG 07:48:10.032] proto_core::version_detector  Detected version from environment variable  tool="deno" env_var="PROTO_DENO_VERSION" version="canary"
[DEBUG 07:48:10.032] proto_core::flow::resolve  Resolving a semantic version or alias  tool="deno" initial_version="canary"
[DEBUG 07:48:10.032] proto_core::flow::resolve  Resolved to canary (without validation)  tool="deno" version="canary"
[DEBUG 07:48:10.032] proto_core::flow::setup  Checking if tool is installed  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/canary"
[DEBUG 07:48:10.032] proto_core::flow::setup  Tool has not been installed  tool="deno"
[TRACE 07:48:10.033] starbase::app  Running shutdown phase (because another phase failed)
Error: proto::tool::required

  × This project requires Deno canary, but this version has not been installed. Install it with proto install deno canary, or enable the auto-install setting to automatically install
  │ missing versions!
```

### Operating system?

Linux

### Architecture?

x64

### PR DESCRIPTION
**Pull request by shanipribadi**
This PR is a proposal to fix #618

### CODE REVIEW

**Comment by shanipribadi** [comment]
Note this PR works for force reinstall of canary
```
PROTO_LOG=trace proto install --force deno canary

[DEBUG 09:10:18.291] proto_core::flow::resolve  Resolving a semantic version or alias  tool="deno" initial_version="canary"
[DEBUG 09:10:18.291] proto_core::flow::resolve  Resolved to canary (without validation)  tool="deno" version="canary"
[DEBUG 09:10:18.292] proto::commands::install  Installing Deno with version canary (from canary)
```

but
```
PROTO_LOG=trace proto install --force deno 1.46.3

[TRACE 09:09:44.412] proto_core::version_resolver  Resolving a version with manifest  candidate="1.46.3"
[TRACE 09:09:44.412] proto_core::version_resolver  Found an explicit version, resolving further  version="1.46.3"
[TRACE 09:09:44.412] proto_core::version_resolver  Resolved to locally installed version  version="1.46.3"
[DEBUG 09:09:44.412] proto_core::flow::resolve  Resolved to 1.46.3  tool="deno" version="1.46.3"
[DEBUG 09:09:44.412] proto_core::flow::setup  Checking if tool is installed  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/1.46.3"
[DEBUG 09:09:44.412] proto_core::flow::setup  Tool has already been installed, locating binaries and shims  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/1.46.3"
```
still consider it as installed, so still need to trace the necessary code changes needed so that --force also works for normal version spec.

**Comment by shanipribadi** [comment]
Okay updating the PR again

```
PROTO_LOG=trace proto install deno canary
[DEBUG 09:27:28.215] proto_core::flow::resolve  Resolving a semantic version or alias  tool="deno" initial_version="canary"
[DEBUG 09:27:28.215] proto_core::flow::resolve  Resolved to canary (without validation)  tool="deno" version="canary"
[DEBUG 09:27:28.215] proto_core::flow::setup  Checking if tool is installed  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/canary"
[DEBUG 09:27:28.215] proto_core::flow::setup  Tool has already been installed, locating binaries and shims  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/canary"
```

```
PROTO_LOG=trace proto install deno 1.46.3
[TRACE 09:27:33.798] proto_core::version_resolver  Resolving a version with manifest  candidate="1.46.3"
[TRACE 09:27:33.798] proto_core::version_resolver  Found an explicit version, resolving further  version="1.46.3"
[TRACE 09:27:33.798] proto_core::version_resolver  Resolved to locally installed version  version="1.46.3"
[DEBUG 09:27:33.798] proto_core::flow::resolve  Resolved to 1.46.3  tool="deno" version="1.46.3"
[DEBUG 09:27:33.798] proto_core::flow::setup  Checking if tool is installed  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/1.46.3"
[DEBUG 09:27:33.798] proto_core::flow::setup  Tool has already been installed, locating binaries and shims  tool="deno" install_dir="/home/shanipribadi/.proto/tools/deno/1.46.3"
```

```
PROTO_LOG=trace proto install --force deno canary
[DEBUG 09:26:47.581] proto_core::flow::resolve  Resolving a semantic version or alias  tool="deno" initial_version="canary"
[DEBUG 09:26:47.581] proto_core::flow::resolve  Resolved to canary (without validation)  tool="deno" version="canary"
[DEBUG 09:26:47.581] proto::commands::install  Installing Deno with version canary (from canary)
```

```
PROTO_LOG=trace proto install --force deno 1.46.3
[TRACE 09:26:52.854] proto_core::version_resolver  Resolving a version with manifest  candidate="1.46.3"
[TRACE 09:26:52.854] proto_core::version_resolver  Found an explicit version, resolving further  version="1.46.3"
[TRACE 09:26:52.854] proto_core::version_resolver  Resolved to locally installed version  version="1.46.3"
[DEBUG 09:26:52.854] proto_core::flow::resolve  Resolved to 1.46.3  tool="deno" version="1.46.3"
[DEBUG 09:26:52.854] proto::commands::install  Installing Deno with version 1.46.3 (from 1.46.3)
```

**Comment by shanipribadi** [comment]
also works as expected for

```
proto install deno latest # does not reinstall if latest is already installed
```

```
proto install deno --force latest # reinstall even if latest is already installed
```

**Comment by milesj** [comment]
@shanipribadi This change looks good. Can you just add some tests to cover it.

**Comment by shanipribadi** [comment]
@milesj can you guide me on where to add some test to cover it, or if there's an existing tests I can base it off? sorry I'm not familiar with rust,
and I didn't find any #[test] in cli/src/commands/install.rs and core/src/flow/install.rs I can use as an example..

**Comment by milesj** [comment]
@shanipribadi Tests are here: https://github.com/moonrepo/proto/blob/master/crates/cli/tests/install_uninstall_test.rs

**Comment by shanipribadi** [comment]
@milesj I have added a test on install_uninstall_test, and asserted the output message as well as the file's mtime to check if it did get reinstalled or not.

**Comment by milesj** [comment]
This looks great! Let's see if tests pass.

**Comment by shanipribadi** [comment]
Looks like windows test failed
```
   3: install_uninstall_test::install_uninstall::install_and_reinstall_canary_tool
             at .\tests\install_uninstall_test.rs:124
 
 assert!(tool_bin.exists());
 ```
 
 my immediate guess is that the file in windows would be `node.exe`, whereas tool_bin path is `node`.
 Hence the failure of that assert.
 
 Is it possible to have a cfg on the OS, for the statement that define the tool_bin path?
 so that on linux/mac it is `node` but on windows it is `node.exe` ?

**Comment by shanipribadi** [comment]
ah okay, so on windows the path is `node/canary/node.exe` as opposed to linux/mac `node/canary/bin/node`

```
❯ ls C:\Users\shani\.proto\tools\node\canary

    Directory: C:\Users\shani\.proto\tools\node\canary

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           9/28/2024 12:28 AM                node_modules
-a---           9/28/2024 12:28 AM          54939 CHANGELOG.md
-a---           9/28/2024 12:28 AM            334 corepack
-a---           9/28/2024 12:28 AM            218 corepack.cmd
-a---           9/28/2024 12:28 AM           3033 install_tools.bat
-a---           9/28/2024 12:28 AM         139053 LICENSE
-a---           9/28/2024 12:28 AM       82113688 node.exe
-a---           9/28/2024 12:28 AM            702 nodevars.bat
-a---           9/28/2024 12:28 AM           2073 npm
-a---           9/28/2024 12:28 AM            538 npm.cmd
-a---           9/28/2024 12:28 AM            795 npm.ps1
-a---           9/28/2024 12:28 AM           2073 npx
-a---           9/28/2024 12:28 AM            538 npx.cmd
-a---           9/28/2024 12:28 AM            795 npx.ps1
-a---           9/28/2024 12:28 AM          40686 README.md
```

**Comment by shanipribadi** [comment]
I found example of
```
if cfg!(windows) {
} else {
}
```
in one of the test, let me add that.

**Comment by milesj** [comment]
Yeah you can just do something like this: `join(if cfg!(windows) { "node.exe" } else { "bin/node" })`

**Comment by shanipribadi** [comment]
ah, that's a shorter way to do it :-), i've pushed a more verbose if else,
didn't realize you could do the if else inside the join itself :-D.

**Comment by shanipribadi** [comment]
it's green ヽ (･ω･ゞ)  !!!

**Comment by milesj** [comment]
Thanks a bunch, will publish now!

**Pull request merged**
